
modLoader = "javafml"
loaderVersion = "[47,)"
license = "All Rights Reserved"
[[mods]]
modId = "kubejsbotanypots"
version = "${file.jarVersion}"
displayName = "KubejsBotanyPots"
authors = "BobVarioa"
description = ""
[[dependencies.kubejsbotanypots]]
    modId = "forge"
    mandatory = true
    versionRange = "[47,)"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.kubejsbotanypots]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.20.1,)"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.kubejsbotanypots]]
    modId = "botanypots"
    mandatory = true
    versionRange = "[13.0.17,)"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.kubejsbotanypots]]
    modId = "kubejs"
    mandatory = true
    versionRange = "[2001.6.4-build.95,)"
    ordering = "NONE"
    side = "BOTH"