
modLoader = "javafml"
loaderVersion = "[43,)"
license = "All Rights Reserved"
[[mods]]
modId = "kubejsbotanypots"
version = "${file.jarVersion}"
displayName = "KubejsBotanyPots"
authors = "BobVarioa"
description = ""
[[dependencies.kubejsbotanypots]]
    modId = "forge"
    mandatory = true
    versionRange = "[43,)"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.kubejsbotanypots]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.19.2,1.20)"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.kubejsbotanypots]]
    modId = "botanypots"
    mandatory = true
    versionRange = "[9.0.27,)"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.kubejsbotanypots]]
    modId = "kubejs"
    mandatory = true
    versionRange = "[1902.6.1-build.234,)"
    ordering = "NONE"
    side = "BOTH"